spring.datasource.url=jdbc:h2:file:./.localdb/mutfak_asistanim;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=USER
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=PUBLIC
app.local-demo.username=edaybasn
app.local-demo.password=12345
app.local-demo.first-name=Eda
app.local-demo.last-name=Ybasn
app.local-demo.email=edaybasn@local.mutfak
